---
 - name: "check site responding"
   shell: "curl -I http://{{ site }}"
   register: homepage_header

 - name: "validate request headers"
   command: "echo 'checking headers'"
   failed_when: "'200' not in '{{ homepage_header.stdout }}'"
