---
 - name: "create {{ workspace }}/htdocs"
   file: path="{{ workspace }}/htdocs" state="directory"
   delegate_to: 127.0.0.1

 - name: "consolidate site htdocs"
   shell: "cp -R {{ workspace }}/*/htdocs {{ workspace }}"
   delegate_to: 127.0.0.1
