---
 - name: "debug git repo"
   debug: msg="{{ repository }}"
   when: false

 - name: "clone repository {{ repository }}"
   git: repo="{{ repository }}" dest="{{ workspace }}/{{ repository | basename }}"
   delegate_to: 127.0.0.1
