---
 - name: "debug git repo"
   debug: msg="{{ repository }}"
   delegate_to: 127.0.0.1
   when: "{{ debug | default(false) }}"

 - name: "clone repository {{ repository }}"
   git: repo="{{ repository }}" dest="{{ workspace }}/{{ repository | basename }}"
   delegate_to: 127.0.0.1
   skip_when: "repository.find('foo.bar') != -1"
